<!doctype html>
<html ng-app="myApp">
<head>
    <meta charset="UTF-8" />
    <title>Teste Social Base</title>
    <link href="css/bootstrap.min.css" media="screen" rel="stylesheet" type="text/css" />
</head>
<body>

<!-- Wrap all page content here -->
<div id="wrap">

    <!-- Fixed navbar -->
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Teste Social Base</a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="#/post-comentario">Mensagem</a></li>
                    
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </div>

    <?=$this->content;?>

    
</div>

<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.13/angular.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.13/angular-route.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.13/angular-resource.min.js"></script>
<script src="projetoangular/app.js"></script>
<script src="projetoangular/controllers.js"></script>
<script src="projetoangular/services.js"></script>

</body>
</html>