<!doctype html>
<html ng-app="Post">
<head>
    <meta charset="UTF-8" />
    <title>Teste social Base</title>
    <link href="css/bootstrap.min.css" media="screen" rel="stylesheet" type="text/css" />
</head>
<body>

<!-- Wrap all page content here -->
<div id="wrap">

    <!-- Fixed navbar -->
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
              
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="#/post-comentario"><h3>Postar Comentário</h3>	</a></li>
                    
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </div>
<div class="container" ng-controller = "PostCtlr">
	
	<br>
	<br>
	<div ng-view></div>
	

</div>
    <?=$this->content;?>

    </div>

<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.13/angular.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.13/angular-route.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.13/angular-resource.min.js"></script>
<script src="socialbaseAngular/Post.js"></script>
<script src="socialbaseAngular/PostCtlr.js"></script>
<script src="socialbaseAngular/postSrv.js"></script>

</body>
</html>